name: Distill CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Distill.sln

    - name: Run unit tests
      run: dotnet test Distill.Tests/Distill.Tests.csproj --configuration ${{ matrix.configuration }} --no-restore --verbosity normal

    - name: Build Distill Solution
      run: dotnet build Distill.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Upload Build Artifacts (Release only)
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: Distill-WinUI3-Release
        path: Distill.App/bin/Release/net8.0-windows10.0.19041.0/
